<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SelfContained>false</SelfContained>
    <AssemblyName>USBManagerWinBackEnd</AssemblyName>
    <RootNamespace>USBManagerWinBackEnd</RootNamespace>
  </PropertyGroup>
  <Target Name="CreateDoubleClickLaunchers" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).exe" DestinationFiles="$(TargetDir)USBManagerWinBackEnd.Install.exe" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).exe" DestinationFiles="$(TargetDir)USBManagerWinBackEnd.Uninstall.exe" />
  </Target>
  <Target Name="CreatePublishedDoubleClickLaunchers" AfterTargets="Publish">
    <Copy SourceFiles="$(PublishDir)USBManagerWinBackEnd.exe" DestinationFiles="$(PublishDir)USBManagerWinBackEnd.Install.exe" />
    <Copy SourceFiles="$(PublishDir)USBManagerWinBackEnd.exe" DestinationFiles="$(PublishDir)USBManagerWinBackEnd.Uninstall.exe" />
  </Target>
</Project>
